---
name: CMake
on: [push, pull_request]
env:
  BUILD_DIR: "${{ github.workspace }}/build/"
  BUILD_TYPE: 'Release'
  CMAKE_FLAGS: >-
    -DENABLE_STATIC=OFF
    -DWITH_BZIP2=OFF
    -DWITH_GEOJSON=OFF
    -DWITH_X11=ON

jobs:
  build:
    runs-on: 'ubuntu-latest'
    container: 'bergentroll/wyrmgus:latest'
    steps:
      - uses: actions/checkout@v2
      - name: Configure CMake
        run: >-
          cmake -S "$GITHUB_WORKSPACE" -B "$BUILD_DIR"
          -D CMAKE_BUILD_TYPE="$BUILD_TYPE" $CMAKE_FLAGS
      - name: Build
        run: cmake --build "$BUILD_DIR" --config "$BUILD_TYPE"
      - name: Test
        run: cmake --build "$BUILD_DIR" --traget test
