---
name: CMake
on: [push, pull_request]
env:
  BUILD_DIR: "${{ github.workspace }}/build/"
  BUILD_TYPE: 'Release'
  CMAKE_FLAGS: >-
    -DENABLE_STATIC=OFF
    -DOpenGL_GL_PREFERENCE=GLVND
    -DWITH_BZIP2=OFF
    -DWITH_GEOJSON=OFF
    -DWITH_X11=ON
  DISPLAY: :0

jobs:
  build:
    runs-on: 'ubuntu-latest'
    container: 'bergentroll/wyrmgus:focal'
    steps:
      - uses: actions/checkout@v2
      - name: Set CPU number
        run: echo "THREADS=$(nproc)" >> "$GITHUB_ENV"
      - name: Configure CMake
        run: >-
          cmake
          -S "$GITHUB_WORKSPACE"
          -B "$BUILD_DIR"
          -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
          $CMAKE_FLAGS
      - name: Workaround for tolua.cpp target on CMake 3.16.3
        run: cmake -S "$GITHUB_WORKSPACE" -B "$BUILD_DIR"
      - name: Build Wyrmgus
        run: >-
          cmake
          --build "$BUILD_DIR"
          --target stratagus_main
          --parallel "$THREADS"
      - name: Build Wyrmgus test suite
        run: >-
          cmake
          --build "$BUILD_DIR"
          --target stratagus_test
          --parallel "$THREADS"
      - name: Test
        continue-on-error: true
        run: cmake --build "$BUILD_DIR" --target test
      - name: Clone Wyrmsun data
        run: git clone https://github.com/Andrettin/Wyrmsun
      - name: Run background services
        run: pulseaudio --exit-idle-time=-1 & Xvfb &
      - name: Run Wyrmsun
        run: >-
          "${BUILD_DIR}/wyrmgus" -t -d "${BUILD_DIR}/Wyrmsun"
        timeout-minutes: 5
